[project]
name = "realtime-stt-chat-script"
version = "0.1.0"
description = ""
authors = [
    { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy (>=1.15.0,<2.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "sounddevice (>=0.5.1,<0.6.0)",
    "numpy (>=2.2.3,<3.0.0)",
    "websocket-client (>=1.8.0,<2.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "websockets (>=15.0,<16.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false


[tool.mypy]
python_version = "3.13"
strict = true
namespace_packages = true
exclude = "(^|/|\\\\)venv($|/|\\\\)"
[[tool.mypy.overrides]]
module = "sounddevice.*"
ignore_missing_imports = true
